### ISSUE TITLE
[Up]: Output progress of translation as part of compilation

### ISSUE THREAD

**Issue by Maxopoly** [tcgdex/cards-database#141]
### Data affected

- [ ] Card
- [ ] Set
- [ ] Serie
- [X] Other
- [ ] new Data Type

### Please explain in more details what idea you have

Autogenerated output to track translation progress would be great. Would likely need to collect base data first on which sets released in which language.

**Comment by Aviortheking** [comment]
Awesome Project Status page

Beautifully made with the latest Generation of HTML and CSS lol

To be serious This is what the status page will looks like, I just need some optimisations as to not keep the whole page in memory

![image](https://user-images.githubusercontent.com/15822031/142884135-2d8d43dd-a712-475f-8fbf-a7998af3c46d.png)

**Comment by Aviortheking** [comment]
There we go !

The Status page 

It now is way quicker to generate have non english sets (mcdo French ones) more nive colors, a legend, and I think thats it !

What do you think of it @Maxopoly ?

![image](https://user-images.githubusercontent.com/15822031/143012400-e6f42ae9-3074-446f-ad00-4c5a623d3033.png)

**Comment by Maxopoly** [comment]
Very cool. Multiple optional/nice to have suggestions:

- The usual intuitive UI color scheme is green, yellow, red from best to worst. Yellow as best and green as intermediate the way you have it is a bit confusing.
- Could even do a linear RGB scale from dark red to light green based on completion rate
- Missing cards and missing info being separate colors seems logically wrong as there are cases in which both are the case. It's also redundant with the completion rate being split into cards and images each. I'd remove these colors and only show a color indicating completion based on the value contained (scaling from red to green, maybe blue if 100 % to discern it clearly from close to completion). Same for the top parts showing per language progress, which I'd also separate into cards and images.
- Black for non-existent sets is a bit too strong of a color. When looking at the page it's the thing that jumps to the eye the most, I'd recommend gray, maybe with slightly darker gray diagonal stripes across. Something that traditionally represents disabled/doesn't exist in UI.
- It'd be great to be able to retrieve what is actually missing to be able to focus on contributing that. Best would be being able to click on an entry to get a detailed view of what does and doesn't exist, but any form of data dump would also be fine. That was the original motivation behind this feature request.
- Add a reference/link to the status page to the README. If you want it very fancy, eventually have an extra status page containing only the top summary and embed in the README to automate display of progress there.
- For each set and series, make the id link to the relevant folder in this github repo for quick access
- Slap some generic CSS for pretty tables onto it

**Comment by Aviortheking** [comment]
> The usual intuitive UI color scheme is green, yellow, red from best to worst. Yellow as best and green as intermediate the way you have it is a bit confusing.

> Could even do a linear RGB scale from dark red to light green based on completion rate

> Missing cards and missing info being separate colors seems logically wrong as there are cases in which both are the case. It's also redundant with the completion rate being split into cards and images each. I'd remove these colors and only show a color indicating completion based on the value contained (scaling from red to green, maybe blue if 100 % to discern it clearly from close to completion).

The base idea was to have a sort of easy to see colors with "Gold" as finished and the two other colors just randomly selected but for global comprehension, I will changes the colors to Green for complete, Yellow to missing something and Red to everything is missing.

I don't think having scaling shown is a good idea (for me at least), because people (myself included) will probably just don't even try to see what is missing with a bright green if only 1 or 2 cards are missing.

For the Images separation this is correct, I chose another color when the two elements were merged in one cell but kept it when separating them

> Same for the top parts showing per language progress, which I'd also separate into cards and images.

The top charts are actually been edited to show that already :D

> Add a reference/link to the status page to the README. If you want it very fancy, eventually have an extra status page containing only the top summary and embed in the README to automate display of progress there.

Yeah, I'll definitivelly make a SVG to quickly fetch the status !

> Black for non-existent sets is a bit too strong of a color. When looking at the page it's the thing that jumps to the eye the most, I'd recommend gray, maybe with slightly darker gray diagonal stripes across. Something that traditionally represents disabled/doesn't exist in UI.

Ok for the dark gray, the stripe won't be set as they are not quite as easy to implement as the color change.

> For each set and series, make the id link to the relevant folder in this github repo for quick access

Yep, that's a good idea !

> Slap some generic CSS for pretty tables onto it

The main goal wasn't to be beautifull at least for a starter, but I will certainly implement my tables CSS after I completed the API Documentation !

> It'd be great to be able to retrieve what is actually missing per set to be able to focus on contributing that. Best would be being able to click on an entry to get a detailed view of what does and doesn't exist, but any form of data dump would also be fine. That was the original motivation behind this feature request.

Adding a Button that fetch the missing cards is a pretty nice feature !

---------------

Also I didn't even give you the live URL: https://api.tcgdex.net/status

So the new goal in the short term are:

- [ ] Add a button that give you the missing cards IDs
- [ ] Add links to directly go to the set/serie
- [ ] Change colors to be more clear
- [ ] Make a .svg file that generate the top Table for README display

In the long term (After finishing the Documentation):

- [ ] Redesign the whole page to be easier on the eyes
