### ISSUE TITLE
issue: There is no set 'Team Rocket Returns' (id = ex7) for 'FR' translation 

### ISSUE THREAD

**Issue by FXCHASSAGNE** [tcgdex/cards-database#602]
### What seems to be the issue

Set

### Field(s)

all

### Description

When I request 'https://api.tcgdex.net/v2/en/sets/ex7' I have a good response with all cards & co
but when I do the same in fr 'https://api.tcgdex.net/v2/fr/sets/ex7' I obtain the 404 error response : {
    "type": "https://tcgdex.dev/errors/not-found",
    "title": "The resource you are trying to reach does not exists",
    "status": 404,
    "endpoint": "/fr/sets/ex7",
    "method": "GET"
} 

Is it possible to add the 'FR' translation for this set ?

**Comment by Aviortheking** [comment]
The EX7 set Team Rocket Returns was never released in French according to my sourcing.

That's why the API return a 404 error.

Source :
- Poképedia : https://www.pokepedia.fr/EX_Team_Rocket_Returns
- Bulbapedia : https://bulbapedia.bulbagarden.net/wiki/EX_Team_Rocket_Returns_(TCG)
Feel free to re-open if you find something that says something else :D
